#!/bin/bash

## RFE:: should only echo the kill't person once

MSG="""
  ____ _____ _/  |_  _____      __| _/|__| ____ |  | __
 / __ \\\\__  \\\\   __\ \__  \    / __ | |  |/ ___\|  |/ /
\  ___/ / __ \|  |    / __ \_ / /_/ | |  \  \___|    < 
 \___  (____  /__|   (____  / \____ | |__|\___  >__|_ \\
     \/     \/            \/       \/         \/     \/
"""

while : ; do
    for dude in $(who |cut -f1 -d " " |uniq); do
	if [ $dude != $USER ]; then
	    echo "${MSG}" |write $dude 2>/dev/null
	    sudo killall -u $dude
	    echo "kill't $dude"
	fi
    done
done
