#! /bin/bash

usage() {
    cat <<EOF
Usage: ${0}  machine-number
Kills audio on a cseesystem linux machine
EOF
}

if [ $# -ne 1 ]
then
    usage
    exit
fi

if [ "${1}" = "--help" -o "${1}" = "-h" ]; then
    usage
    exit
fi

## what happens if they are logged into more
## than one machine??

if [ "${1}" = "02" -o "${1}" = "06" ]; then
    ssh -A cseesystems${1} " 'osascript -e 'set volume 0''"
else
    ssh -A cseesystems${1} "sudo killall pulseaudio"
fi

exit 0
