#! /bin/bash

usage() {
    cat <<EOF
Usage: ${0}  machine-number
Kills audio on a cseesystem linux machine
EOF
}

if [ $# -lt 1 ]
then
    usage
    exit
fi

if [ "${1}" = "--help" -o "${1}" = "-h" ]; then
    usage
    exit
fi

for host in "$@"; do
    if [ "$host" = "02" -o "$host" = "06" ]; then
	ssh -A cseesystems${1} " 'osascript -e 'set volume 0''"
    else
	ssh -A cseesystems${1} "sudo killall pulseaudio"
    fi
done

exit 0
